return {
  numeric = {
    [1] = "󰎤",
    [2] = "󰎧",
    [3] = "󰎪",
    [4] = "󰎭",
    [5] = "󰎱",
    [6] = "󰎳",
    [7] = "󰎶",
    [8] = "󰎹",
    [9] = "󰎼",
    [10] = "󰎡",
  },

  severity = {
    [1] = { icon = "", hl = "DiagnosticError" },
    [2] = { icon = "", hl = "DiagnosticWarn" },
    [3] = { icon = "", hl = "DiagnosticInfo" },
    [4] = { icon = "", hl = "DiagnosticHint" },
  },

  diff = {
    hunk_del = "",
    hunk_add = "",
    hunk_sign = "",
    add = "󰐖",
    delete = "󰍵",
  },

  tag = {
    param = "󰏪",
    returns = "󰌑",
    brief = "󰧭",
    throws = "󰚑",
    see = "󰈈",
    since = "󰔠",
    deprecated = "󰃤",
    note = "󰍩",
    example = "",
    version = "󰜣",
    link = "󰌹",
    default = "󰁕",
    type = "󰠱",
    type_param = "󰗴",
    field = "󰜢",
    enum = "󰕘",
    interface = "󰜰",
    module = "󰅩",
    func = "󰊕",
    sealed = "󰌾",
    event = "󰀦",
    package = "󰏗",
    label = "󰓹",
    variable = "󰀫",
    experimental = "󰂡",
    public = "󰡁",
    internal = "󰒃",
  },

  ui = {
    server = "󰚗",
    file = "󰈙",
    content = "󰧭",
    code = "󰓹",
    loading = "󰔟",
    info = "󰍻",
    error = "",
    symbol_fallback = "󰈚",
  },
}
