local g = require("lemon.glyph").tag

---@type table<string, Lemon.TagDef>
return {
  ["@param"] = { icon = g.param, hl = "LemonTitle" },
  ["@returns?"] = { icon = g.returns, hl = "@keyword.return" },
  ["@version"] = { icon = g.version, hl = "@number" },
  ["@see"] = { icon = g.see, hl = "@markup.link" },
  ["@example"] = { icon = g.example, hl = "@function" },
  ["@throws"] = { icon = g.throws, hl = "DiagnosticWarn" },
  ["@deprecated"] = { icon = g.deprecated, hl = "DiagnosticError" },
  ["@since"] = { icon = g.since, hl = "@number" },
  ["@author"] = { icon = g.param, hl = "@variable" },
  ["@link"] = { icon = g.link, hl = "@markup.link" },
  ["@default"] = { icon = g.default, hl = "@constant" },
  ["@defaultValue"] = { icon = g.default, hl = "@constant" },
  ["@type"] = { icon = g.type, hl = "@type" },
  ["@typeParam"] = { icon = g.type_param, hl = "@type" },
  ["@class"] = { icon = g.type, hl = "@type" },
  ["@field"] = { icon = g.field, hl = "@variable.member" },
  ["@alias"] = { icon = g.link, hl = "@type" },
  ["@enum"] = { icon = g.enum, hl = "@type" },
  ["@interface"] = { icon = g.interface, hl = "@type" },
  ["@module"] = { icon = g.module, hl = "@module" },
  ["@generic"] = { icon = g.type_param, hl = "@type" },
  ["@overload"] = { icon = g.func, hl = "@function" },
  ["@override"] = { icon = g.func, hl = "@function" },
  ["@virtual"] = { icon = g.func, hl = "@function" },
  ["@sealed"] = { icon = g.sealed, hl = "@keyword" },
  ["@readonly"] = { icon = g.sealed, hl = "@keyword" },
  ["@decorator"] = { icon = g.deprecated, hl = "@attribute" },
  ["@eventProperty"] = { icon = g.event, hl = "@variable.member" },
  ["@inheritDoc"] = { icon = g.see, hl = "@markup.link" },
  ["@remarks"] = { icon = g.note, hl = "DiagnosticInfo" },
  ["@privateRemarks"] = { icon = g.note, hl = "DiagnosticHint" },
  ["@packageDocumentation"] = { icon = g.package, hl = "@module" },
  ["@label"] = { icon = g.label, hl = "@label" },
  ["@alpha"] = { icon = g.variable, hl = "DiagnosticWarn" },
  ["@beta"] = { icon = g.experimental, hl = "DiagnosticWarn" },
  ["@experimental"] = { icon = g.experimental, hl = "DiagnosticWarn" },
  ["@public"] = { icon = g.public, hl = "@keyword" },
  ["@internal"] = { icon = g.internal, hl = "DiagnosticHint" },
  ["@brief"] = { icon = g.brief, hl = "LemonTitle" },
}
