---@type table<string, Lemon.TagDef>
return {
  ["@param"] = { icon = "󰏪", hl = "LemonTitle" },
  ["@returns?"] = { icon = "󰌑", hl = "@keyword.return" },
  ["@version"] = { icon = "󰜣", hl = "@number" },
  ["@see"] = { icon = "󰈈", hl = "@markup.link" },
  ["@example"] = { icon = "", hl = "@function" },
  ["@throws"] = { icon = "󰚑", hl = "DiagnosticWarn" },
  ["@deprecated"] = { icon = "󰃤", hl = "DiagnosticError" },
  ["@since"] = { icon = "󰔠", hl = "@number" },
  ["@author"] = { icon = "󰏪", hl = "@variable" },
  ["@link"] = { icon = "󰌹", hl = "@markup.link" },
  ["@default"] = { icon = "󰁕", hl = "@constant" },
  ["@defaultValue"] = { icon = "󰁕", hl = "@constant" },
  ["@type"] = { icon = "󰠱", hl = "@type" },
  ["@typeParam"] = { icon = "󰗴", hl = "@type" },
  ["@class"] = { icon = "󰠱", hl = "@type" },
  ["@field"] = { icon = "󰜢", hl = "@variable.member" },
  ["@alias"] = { icon = "󰌹", hl = "@type" },
  ["@enum"] = { icon = "󰕘", hl = "@type" },
  ["@interface"] = { icon = "󰜰", hl = "@type" },
  ["@module"] = { icon = "󰅩", hl = "@module" },
  ["@generic"] = { icon = "󰗴", hl = "@type" },
  ["@overload"] = { icon = "󰊕", hl = "@function" },
  ["@override"] = { icon = "󰊕", hl = "@function" },
  ["@virtual"] = { icon = "󰊕", hl = "@function" },
  ["@sealed"] = { icon = "󰌾", hl = "@keyword" },
  ["@readonly"] = { icon = "󰌾", hl = "@keyword" },
  ["@decorator"] = { icon = "󰃤", hl = "@attribute" },
  ["@eventProperty"] = { icon = "󰀦", hl = "@variable.member" },
  ["@inheritDoc"] = { icon = "󰈈", hl = "@markup.link" },
  ["@remarks"] = { icon = "󰍩", hl = "DiagnosticInfo" },
  ["@privateRemarks"] = { icon = "󰍩", hl = "DiagnosticHint" },
  ["@packageDocumentation"] = { icon = "󰏗", hl = "@module" },
  ["@label"] = { icon = "󰓹", hl = "@label" },
  ["@alpha"] = { icon = "󰀫", hl = "DiagnosticWarn" },
  ["@beta"] = { icon = "󰂡", hl = "DiagnosticWarn" },
  ["@experimental"] = { icon = "󰂡", hl = "DiagnosticWarn" },
  ["@public"] = { icon = "󰡁", hl = "@keyword" },
  ["@internal"] = { icon = "󰒃", hl = "DiagnosticHint" },
  ["@brief"] = { icon = "󰧭", hl = "LemonTitle" },
}
